/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "MyWeb": {
      "type": "sst.aws.Remix"
      "url": string
    }
    "Puppeteer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Titles": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
